### ISSUE TITLE
Fem steg om hvordan vi involverer brukere i produktutviklingen

### ISSUE THREAD

**Issue by alisekjelling** [Altinn/info.altinn.no#461]
Følger opp issue Altinn/altinn-infoportal-optimizely#132 
Vi har laget en overordnet "guide" til hvordan produktteam kan involvere brukere. Det er delt inn i fem steg. Målet er at det skal være lett å komme i gang med brukerinvolvering. I de fem stegene er det lenker til både eksisterende og nye ressurser (f.eks. råd om hvilke metoder som passer til hva). Det gjenstår å lage noen av ressursene vi trenger. De fem stegene skal bo på Baksia. 

Arbeid som gjenstår:

```[tasklist]
### Tasks
- [ ] Publisere på Baksia
- [ ] Snakke med team om å teste/pilotere
- [ ] Informere internt om at det er på Baksia
- [ ] Lage flere ressurser
```

`
